---


- name: check required vars
  fail:
    msg: "password_secret or/and root_password_sha2 is not defined"
  when: not graylog_password_secret and not graylog_root_password_sha2


- name: start mongod
  service:
    name: mongod
    state: started
    enabled: yes


- name: edit server.conf
  template:
    backup: yes
    src: server.conf.j2
    dest: /etc/graylog/server/server.conf
  register: config


- name: edit graylog-server default
  template:
    src: graylog-server.j2
    dest: /etc/sysconfig/graylog-server
  register: default


- name: create journal directory
  file:
    dest: /var/lib/graylog-server/journal
    state: directory
    owner: graylog
    group: graylog

   
- name: restart graylog server
  service:
    name: graylog-server
    state: restarted
    enabled: yes
  when: config.changed or default.changed


- name: start graylog-server
  service:
    name: graylog-server
    state: started
    enabled: yes
