---


- include: install_debian.yml
  tags: install
  when: ansible_os_family == "Debian"


- include: install_redhat.yml
  tags: install
  when: ansible_os_family == "RedHat"


- include: configure.yml
  tags: configure